epochs: 50
resume: None
learning_rate: 2e-2
weight_decay: 10e-6
inference_device: "cuda"
SEED: 42

train:
  batch_size: 12
  num_workers: 4
  valid_size: 0.2
  train_path: "../dataset/train"
  image_size: 128

test:
  batch_size: 12
  num_workers: 4
  test_path: "../dataset/test"
  image_size: 128

model:
  base_model: "dacon_landmark"